version: "3.7"

services:
  speakerbob:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DBHOST=postgres
      - DBUSER=speakerbob
      - DBPASSWORD=speakerbob
      - DBNAME=speakerbob
      - MINIOHOST=minio:9000
      - MINIOACCESSID=speakerbob
      - MINIOACCESSKEY=speakerbob
      - MINIOUSESSL=false

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=speakerbob
      - POSTGRES_USER=speakerbob
      - POSTGRES_DB=speakerbob

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: speakerbob
      MINIO_SECRET_KEY: speakerbob
    command: server /data

volumes:
  minio:
