version: "3.7"

services:
  speakerbob:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MINIOURL=minio:9000
      - MINIOACCESSID=speakerbob
      - MINIOACCESSKEY=speakerbob
      - MINIOUSESSL=false
      - REDISURL=redis://redis:6379/0

  minio:
    image: minio/minio
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: speakerbob
      MINIO_SECRET_KEY: speakerbob
    command: server /data

volumes:
  minio:
