version: "3.7"

services:
  speakerbob:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DBURL=sqlite3:///etc/speakerbob/speakerbob.db
      - SOUNDBACKENDURL=local:///etc/speakerbob/sounds
    volumes:
      - speakerbob:/etc/speakerbob
      - sounds:/etc/speakerbob/sounds

volumes:
  sounds:
  speakerbob: