version: "3.7"

services:
  speakerbob:
    build: .
    environment:
      - PORT=80
#      - AUTHBACKENDURL=memory://
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web/dist:/var/www
