version: "3.7"

services:
  speakerbob:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - AUTHBACKENDURL=
    volumes:
      - speakerbob:/etc/speakerbob
      - sounds:/etc/speakerbob/sounds

volumes:
  sounds:
  speakerbob: