apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "speakerbob.fullname" . }}
  labels:
    {{- include "speakerbob.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "speakerbob.fullname" . }}
  selector:
    matchLabels:
      {{- include "speakerbob.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "speakerbob.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: speakerbob
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/healthz/
              port: http
          readinessProbe:
            httpGet:
              path: /api/healthz/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - "speakerbob"
          args:
            - "server"
            - "--config"
            - "/config/server.yaml"
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - mountPath: /data
              name: data
            {{- end }}
            - mountPath: /config
              name: config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "speakerbob.persistenceClaim" . }}
        {{- end }}
        - name: config
          secret:
              secretName: {{ include "speakerbob.fullname" . }}-config
              items:
                - key: "server.yaml"
                  path: "server.yaml"
