{{- $fullName := include "speakerbob.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-config
  labels:
    {{- include "speakerbob.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  server.yaml: {{ .Values.configuration | toYaml | b64enc }}