#!/usr/bin/env bash

go mod tidy

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  git --no-pager diff
  exit 1
fi

go fmt ./...

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  git --no-pager diff
  exit 1
fi

go test ./...
