#!/usr/bin/env bash

pushd web/speakerbob
  yarn
  export PATH="$(yarn bin):$PATH"
  yarn lint
popd

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  git --no-pager diff
  exit 1
fi
