#!/usr/bin/env bash

set -euo pipefail
set -x

mkdir -p dist

yq e -i '.version = strenv(CHART_VERSION)' charts/speakerbob/Chart.yaml
yq e -i '.appVersion = strenv(IMAGE_TAG)' charts/speakerbob/Chart.yaml
yq e -i '.info.version = strenv(CHART_VERSION)' docs/asyncapi.yaml
yq e -i '.info.version = strenv(CHART_VERSION)' docs/openapi.yaml

helm package charts/speakerbob -d dist

cp docs/asyncapi.yaml dist/
cp docs/openapi.yaml dist/
