#!/usr/bin/env bash

go mod tidy

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "Go mod is out of date!"
  exit 1
fi

for d in pkg/* ; do
  pushd "$d" || exit
    go fmt .
  popd || exit
done

go fmt main.go
go fmt cmd

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "bad go formatting!"
  exit 1
fi

pushd web/speakerbob
  yarn
  export PATH="$(yarn bin):$PATH"
  yarn lint
popd

if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
  echo "bad js formatting!"
  exit 1
fi

docker build --no-cache .
