name: push image

on:
  push:
    branches:
      - master
      - release/*

jobs:
  push-image:
    name: push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: scripts/version
      - run: docker build --build-arg VERSION=$VERSION -t $IMAGE_NAME:$VERSION .
      - run: docker image tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$IMAGE_TAG
      - run: docker push $IMAGE_NAME:$VERSION
      - run: docker push $IMAGE_NAME:$IMAGE_TAG