name: push image

on:
  push:
    tags:
      - v*

jobs:
  build-assets:
    name: build-assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2
      - run: sudo apt update && sudo apt install gcc-mingw-w64-x86-64 -y
      - run: scripts/build
      - run: docker build --build-arg VERSION=${GITHUB_REF##*/} -t $GITHUB_REPOSITORY:${GITHUB_REF##*/} .
      - run: docker push $GITHUB_REPOSITORY:${GITHUB_REF##*/}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: dist/*
